# Generated by Django 3.1.7 on 2021-05-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Log_Design', 'Log Design'), ('Web_Design', 'Web Design'), ('Print_Design', 'Print Design'), ('Mobile_App_Developer', 'Mobile App Developer'), ('Software_Engineer', 'Software Engineer'), ('DataBase_Engineer', 'DataBase Engineer'), ('System_Engineer', 'System Engineer'), ('Content_Writer', 'Content Writer'), ('Video_Editor', 'Video Editor')], max_length=50),
        ),
    ]
