# Generated by Django 3.1.7 on 2021-05-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20210526_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
