# Generated by Django 3.1.7 on 2021-05-21 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_Local_Police', models.FileField(upload_to='Seeker/Seeker_Request/%d/LP/')),
                ('doc_Gramma_Niladari', models.FileField(upload_to='Seeker/Seeker_Request/%d/GN')),
                ('doc_Divisional_Secretary', models.FileField(upload_to='Seeker/Seeker_Request/%d/DS')),
                ('skills', models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD')))], max_length=50)),
            ],
        ),
    ]
