# Generated by Django 3.1.7 on 2021-05-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0003_seeker_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seeker_Request',
        ),
    ]
