# Generated by Django 3.1.7 on 2021-05-21 06:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0005_seeker_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_request',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD')))], max_length=11),
        ),
    ]
