# Generated by Django 3.1.7 on 2021-05-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0006_auto_20210521_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker_request',
            name='skills',
        ),
    ]
