# Generated by Django 3.1.7 on 2021-05-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0007_remove_seeker_request_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seeker_Request',
        ),
    ]
