# Generated by Django 3.1.7 on 2021-05-21 07:10

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seeker', '0008_delete_seeker_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_Local_Police', models.FileField(upload_to='Seeker/Seeker_Request/%d/LP/')),
                ('doc_Gramma_Niladari', models.FileField(upload_to='Seeker/Seeker_Request/%d/GN')),
                ('doc_Divisional_Secretary', models.FileField(upload_to='Seeker/Seeker_Request/%d/DS')),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Design', (('Logo_Designer', 'Logo Designer'), ('Web_Designer', 'Web Designer'), ('Print_Designer', 'Print Designer'))), ('Technology', (('Mobile_App_Developer', 'Mobile App Developer'), ('Software_Engineer', 'Software Enginner'), ('DataBase_Engineer', 'DataBase Engineer'), ('System_Engineer', 'System Engineer'))), ('Entertainment', (('Content_Writer', 'Content Writer'), ('Video_Editer', 'Video Editer')))], max_length=31)),
            ],
        ),
    ]
