# Generated by Django 3.1.7 on 2021-05-21 13:19

import Seeker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0009_seeker_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker_request',
            name='token',
            field=models.CharField(default=Seeker.models.secret_token, max_length=16),
        ),
    ]
