# Generated by Django 3.1.7 on 2021-05-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0012_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='username',
        ),
    ]
