# Generated by Django 3.1.7 on 2021-05-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0013_remove_seeker_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seeker',
        ),
    ]
