# Generated by Django 3.1.7 on 2021-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_request',
            name='token',
            field=models.CharField(default='092514ba356eaeb0', max_length=16),
        ),
    ]
