# Generated by Django 3.1.7 on 2021-05-21 12:49

import Company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_remove_company_request_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_request',
            name='token',
            field=models.CharField(default=Company.models.secret_token, max_length=16),
        ),
    ]
