# Generated by Django 3.1.7 on 2021-05-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_no',
        ),
    ]
