# Generated by Django 3.1.7 on 2021-05-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_remove_company_contact_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
